"""added boundary table with polygon type

Revision ID: 8ce19d41a4f1
Revises: 08144ce28c39
Create Date: 2025-12-13 01:54:01.826368

"""
from typing import Sequence, Union

from alembic import op # noqa: F401
import sqlalchemy as sa
import geoalchemy2 # noqa: F401


# revision identifiers, used by Alembic.
revision: str = '8ce19d41a4f1'
down_revision: Union[str, Sequence[str], None] = '08144ce28c39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('species_soil_texture_association',
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('soil_texture_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['soil_texture_id'], ['soil_textures.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('species_id', 'soil_texture_id')
    )
    op.create_table('boundary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('boundary', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("DROP INDEX IF EXISTS idx_boundary_boundary;")
    op.create_index('idx_boundary_boundary', 'boundary', ['boundary'], unique=False, postgresql_using='gist')
    op.drop_constraint(op.f('species_preferred_soil_texture_id_fkey'), 'species', type_='foreignkey')
    op.drop_column('species', 'preferred_soil_texture_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('species', sa.Column('preferred_soil_texture_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('species_preferred_soil_texture_id_fkey'), 'species', 'soil_textures', ['preferred_soil_texture_id'], ['id'], ondelete='CASCADE')
    op.drop_index('idx_boundary_boundary', table_name='boundary', postgresql_using='gist')
    op.drop_table('boundary')
    op.drop_table('species_soil_texture_association')
    # ### end Alembic commands ###
